- ch: 54
  name: Прихожая
- ch: 59
  name: Бар
  brightness: true
- ch: 62
  name: У телевизора
  brightness: true
- ch: 63
  name: Свет
- ch: 61
  name: Свечи
- ch: 60
  name: Стеллаж
- ch: 58
  name: на кухне
- ch: 57
  name: стеллаж на кухне
- ch: 56
  name: точки на первом (проверить)
- ch: 54
  name: в прихожей
- ch: 53
  name: на лестнице в подвал
- ch: 52
  name: на лестнице
- ch: 51
  name: на лестнице на третий этаж
- ch: 50
  name: в коридоре на втором этаже
- ch: 49
  name: в коридоре на третьем этаже
- ch: 41
  name: весь свет на первом
- ch: 39
  name: в коридоре на первом
- ch: 38
  name: в проходе
  brightness: true